/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedSimulatorRouteImport } from './routes/_authenticated/simulator'
import { Route as InbjudanTokenRouteImport } from './routes/inbjudan.$token'
import { Route as AuthenticatedForsaljningIndexRouteImport } from './routes/_authenticated/forsaljning.index'
import { Route as AuthenticatedForsaljningSlutavrakningRouteImport } from './routes/_authenticated/forsaljning.slutavrakning'
import { Route as AuthenticatedForsaljningVarderingarRouteImport } from './routes/_authenticated/forsaljning.varderingar'
import { Route as AuthenticatedKontoIndexRouteImport } from './routes/_authenticated/konto.index'
import { Route as AuthenticatedOverenskommelseIndexRouteImport } from './routes/_authenticated/overenskommelse.index'
import { Route as AuthenticatedOverenskommelseKostnadsslagRouteImport } from './routes/_authenticated/overenskommelse.kostnadsslag'
import { Route as AuthenticatedOverenskommelseParterRouteImport } from './routes/_authenticated/overenskommelse.parter'
import { Route as AuthenticatedOverenskommelseTillaggRouteImport } from './routes/_authenticated/overenskommelse.tillagg'
import { Route as AuthenticatedOverenskommelseVersionerRouteImport } from './routes/_authenticated/overenskommelse.versioner'
import { Route as AuthenticatedSystemAnvandareRouteImport } from './routes/_authenticated/system.anvandare'
import { Route as AuthenticatedSystemHushallRouteImport } from './routes/_authenticated/system.hushall'
import { Route as AuthenticatedSystemInbjudningarRouteImport } from './routes/_authenticated/system.inbjudningar'
import { Route as AuthenticatedSystemRevisionRouteImport } from './routes/_authenticated/system.revision'
import { Route as AuthenticatedTransaktionerIndexRouteImport } from './routes/_authenticated/transaktioner.index'
import { Route as AuthenticatedTransaktionerHistorikRouteImport } from './routes/_authenticated/transaktioner.historik'
import { Route as AuthenticatedTransaktionerVantarRouteImport } from './routes/_authenticated/transaktioner.vantar'
import { Route as ApiBilagaIndexRouteImport } from './routes/api/bilaga.index'
import { Route as ApiBilagaIdRouteImport } from './routes/api/bilaga.$id'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSimulatorRoute = AuthenticatedSimulatorRouteImport.update({
  id: '/simulator',
  path: '/simulator',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const InbjudanTokenRoute = InbjudanTokenRouteImport.update({
  id: '/inbjudan/$token',
  path: '/inbjudan/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedForsaljningIndexRoute =
  AuthenticatedForsaljningIndexRouteImport.update({
    id: '/forsaljning/',
    path: '/forsaljning/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedForsaljningSlutavrakningRoute =
  AuthenticatedForsaljningSlutavrakningRouteImport.update({
    id: '/forsaljning/slutavrakning',
    path: '/forsaljning/slutavrakning',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedForsaljningVarderingarRoute =
  AuthenticatedForsaljningVarderingarRouteImport.update({
    id: '/forsaljning/varderingar',
    path: '/forsaljning/varderingar',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedKontoIndexRoute = AuthenticatedKontoIndexRouteImport.update({
  id: '/konto/',
  path: '/konto/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOverenskommelseIndexRoute =
  AuthenticatedOverenskommelseIndexRouteImport.update({
    id: '/overenskommelse/',
    path: '/overenskommelse/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOverenskommelseKostnadsslagRoute =
  AuthenticatedOverenskommelseKostnadsslagRouteImport.update({
    id: '/overenskommelse/kostnadsslag',
    path: '/overenskommelse/kostnadsslag',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOverenskommelseParterRoute =
  AuthenticatedOverenskommelseParterRouteImport.update({
    id: '/overenskommelse/parter',
    path: '/overenskommelse/parter',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOverenskommelseTillaggRoute =
  AuthenticatedOverenskommelseTillaggRouteImport.update({
    id: '/overenskommelse/tillagg',
    path: '/overenskommelse/tillagg',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOverenskommelseVersionerRoute =
  AuthenticatedOverenskommelseVersionerRouteImport.update({
    id: '/overenskommelse/versioner',
    path: '/overenskommelse/versioner',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSystemAnvandareRoute =
  AuthenticatedSystemAnvandareRouteImport.update({
    id: '/system/anvandare',
    path: '/system/anvandare',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSystemHushallRoute =
  AuthenticatedSystemHushallRouteImport.update({
    id: '/system/hushall',
    path: '/system/hushall',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSystemInbjudningarRoute =
  AuthenticatedSystemInbjudningarRouteImport.update({
    id: '/system/inbjudningar',
    path: '/system/inbjudningar',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSystemRevisionRoute =
  AuthenticatedSystemRevisionRouteImport.update({
    id: '/system/revision',
    path: '/system/revision',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTransaktionerIndexRoute =
  AuthenticatedTransaktionerIndexRouteImport.update({
    id: '/transaktioner/',
    path: '/transaktioner/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTransaktionerHistorikRoute =
  AuthenticatedTransaktionerHistorikRouteImport.update({
    id: '/transaktioner/historik',
    path: '/transaktioner/historik',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTransaktionerVantarRoute =
  AuthenticatedTransaktionerVantarRouteImport.update({
    id: '/transaktioner/vantar',
    path: '/transaktioner/vantar',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiBilagaIndexRoute = ApiBilagaIndexRouteImport.update({
  id: '/api/bilaga/',
  path: '/api/bilaga/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBilagaIdRoute = ApiBilagaIdRouteImport.update({
  id: '/api/bilaga/$id',
  path: '/api/bilaga/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthRoute
  '/simulator': typeof AuthenticatedSimulatorRoute
  '/inbjudan/$token': typeof InbjudanTokenRoute
  '/forsaljning/slutavrakning': typeof AuthenticatedForsaljningSlutavrakningRoute
  '/forsaljning/varderingar': typeof AuthenticatedForsaljningVarderingarRoute
  '/overenskommelse/kostnadsslag': typeof AuthenticatedOverenskommelseKostnadsslagRoute
  '/overenskommelse/parter': typeof AuthenticatedOverenskommelseParterRoute
  '/overenskommelse/tillagg': typeof AuthenticatedOverenskommelseTillaggRoute
  '/overenskommelse/versioner': typeof AuthenticatedOverenskommelseVersionerRoute
  '/system/anvandare': typeof AuthenticatedSystemAnvandareRoute
  '/system/hushall': typeof AuthenticatedSystemHushallRoute
  '/system/inbjudningar': typeof AuthenticatedSystemInbjudningarRoute
  '/system/revision': typeof AuthenticatedSystemRevisionRoute
  '/transaktioner/historik': typeof AuthenticatedTransaktionerHistorikRoute
  '/transaktioner/vantar': typeof AuthenticatedTransaktionerVantarRoute
  '/api/bilaga/$id': typeof ApiBilagaIdRoute
  '/forsaljning/': typeof AuthenticatedForsaljningIndexRoute
  '/konto/': typeof AuthenticatedKontoIndexRoute
  '/overenskommelse/': typeof AuthenticatedOverenskommelseIndexRoute
  '/transaktioner/': typeof AuthenticatedTransaktionerIndexRoute
  '/api/bilaga/': typeof ApiBilagaIndexRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/simulator': typeof AuthenticatedSimulatorRoute
  '/inbjudan/$token': typeof InbjudanTokenRoute
  '/': typeof AuthenticatedIndexRoute
  '/forsaljning/slutavrakning': typeof AuthenticatedForsaljningSlutavrakningRoute
  '/forsaljning/varderingar': typeof AuthenticatedForsaljningVarderingarRoute
  '/overenskommelse/kostnadsslag': typeof AuthenticatedOverenskommelseKostnadsslagRoute
  '/overenskommelse/parter': typeof AuthenticatedOverenskommelseParterRoute
  '/overenskommelse/tillagg': typeof AuthenticatedOverenskommelseTillaggRoute
  '/overenskommelse/versioner': typeof AuthenticatedOverenskommelseVersionerRoute
  '/system/anvandare': typeof AuthenticatedSystemAnvandareRoute
  '/system/hushall': typeof AuthenticatedSystemHushallRoute
  '/system/inbjudningar': typeof AuthenticatedSystemInbjudningarRoute
  '/system/revision': typeof AuthenticatedSystemRevisionRoute
  '/transaktioner/historik': typeof AuthenticatedTransaktionerHistorikRoute
  '/transaktioner/vantar': typeof AuthenticatedTransaktionerVantarRoute
  '/api/bilaga/$id': typeof ApiBilagaIdRoute
  '/forsaljning': typeof AuthenticatedForsaljningIndexRoute
  '/konto': typeof AuthenticatedKontoIndexRoute
  '/overenskommelse': typeof AuthenticatedOverenskommelseIndexRoute
  '/transaktioner': typeof AuthenticatedTransaktionerIndexRoute
  '/api/bilaga': typeof ApiBilagaIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/simulator': typeof AuthenticatedSimulatorRoute
  '/inbjudan/$token': typeof InbjudanTokenRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/forsaljning/slutavrakning': typeof AuthenticatedForsaljningSlutavrakningRoute
  '/_authenticated/forsaljning/varderingar': typeof AuthenticatedForsaljningVarderingarRoute
  '/_authenticated/overenskommelse/kostnadsslag': typeof AuthenticatedOverenskommelseKostnadsslagRoute
  '/_authenticated/overenskommelse/parter': typeof AuthenticatedOverenskommelseParterRoute
  '/_authenticated/overenskommelse/tillagg': typeof AuthenticatedOverenskommelseTillaggRoute
  '/_authenticated/overenskommelse/versioner': typeof AuthenticatedOverenskommelseVersionerRoute
  '/_authenticated/system/anvandare': typeof AuthenticatedSystemAnvandareRoute
  '/_authenticated/system/hushall': typeof AuthenticatedSystemHushallRoute
  '/_authenticated/system/inbjudningar': typeof AuthenticatedSystemInbjudningarRoute
  '/_authenticated/system/revision': typeof AuthenticatedSystemRevisionRoute
  '/_authenticated/transaktioner/historik': typeof AuthenticatedTransaktionerHistorikRoute
  '/_authenticated/transaktioner/vantar': typeof AuthenticatedTransaktionerVantarRoute
  '/api/bilaga/$id': typeof ApiBilagaIdRoute
  '/_authenticated/forsaljning/': typeof AuthenticatedForsaljningIndexRoute
  '/_authenticated/konto/': typeof AuthenticatedKontoIndexRoute
  '/_authenticated/overenskommelse/': typeof AuthenticatedOverenskommelseIndexRoute
  '/_authenticated/transaktioner/': typeof AuthenticatedTransaktionerIndexRoute
  '/api/bilaga/': typeof ApiBilagaIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/simulator'
    | '/inbjudan/$token'
    | '/forsaljning/slutavrakning'
    | '/forsaljning/varderingar'
    | '/overenskommelse/kostnadsslag'
    | '/overenskommelse/parter'
    | '/overenskommelse/tillagg'
    | '/overenskommelse/versioner'
    | '/system/anvandare'
    | '/system/hushall'
    | '/system/inbjudningar'
    | '/system/revision'
    | '/transaktioner/historik'
    | '/transaktioner/vantar'
    | '/api/bilaga/$id'
    | '/forsaljning/'
    | '/konto/'
    | '/overenskommelse/'
    | '/transaktioner/'
    | '/api/bilaga/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/simulator'
    | '/inbjudan/$token'
    | '/'
    | '/forsaljning/slutavrakning'
    | '/forsaljning/varderingar'
    | '/overenskommelse/kostnadsslag'
    | '/overenskommelse/parter'
    | '/overenskommelse/tillagg'
    | '/overenskommelse/versioner'
    | '/system/anvandare'
    | '/system/hushall'
    | '/system/inbjudningar'
    | '/system/revision'
    | '/transaktioner/historik'
    | '/transaktioner/vantar'
    | '/api/bilaga/$id'
    | '/forsaljning'
    | '/konto'
    | '/overenskommelse'
    | '/transaktioner'
    | '/api/bilaga'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/simulator'
    | '/inbjudan/$token'
    | '/_authenticated/'
    | '/_authenticated/forsaljning/slutavrakning'
    | '/_authenticated/forsaljning/varderingar'
    | '/_authenticated/overenskommelse/kostnadsslag'
    | '/_authenticated/overenskommelse/parter'
    | '/_authenticated/overenskommelse/tillagg'
    | '/_authenticated/overenskommelse/versioner'
    | '/_authenticated/system/anvandare'
    | '/_authenticated/system/hushall'
    | '/_authenticated/system/inbjudningar'
    | '/_authenticated/system/revision'
    | '/_authenticated/transaktioner/historik'
    | '/_authenticated/transaktioner/vantar'
    | '/api/bilaga/$id'
    | '/_authenticated/forsaljning/'
    | '/_authenticated/konto/'
    | '/_authenticated/overenskommelse/'
    | '/_authenticated/transaktioner/'
    | '/api/bilaga/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  InbjudanTokenRoute: typeof InbjudanTokenRoute
  ApiBilagaIdRoute: typeof ApiBilagaIdRoute
  ApiBilagaIndexRoute: typeof ApiBilagaIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/simulator': {
      id: '/_authenticated/simulator'
      path: '/simulator'
      fullPath: '/simulator'
      preLoaderRoute: typeof AuthenticatedSimulatorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/inbjudan/$token': {
      id: '/inbjudan/$token'
      path: '/inbjudan/$token'
      fullPath: '/inbjudan/$token'
      preLoaderRoute: typeof InbjudanTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/forsaljning/': {
      id: '/_authenticated/forsaljning/'
      path: '/forsaljning'
      fullPath: '/forsaljning/'
      preLoaderRoute: typeof AuthenticatedForsaljningIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/forsaljning/slutavrakning': {
      id: '/_authenticated/forsaljning/slutavrakning'
      path: '/forsaljning/slutavrakning'
      fullPath: '/forsaljning/slutavrakning'
      preLoaderRoute: typeof AuthenticatedForsaljningSlutavrakningRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/forsaljning/varderingar': {
      id: '/_authenticated/forsaljning/varderingar'
      path: '/forsaljning/varderingar'
      fullPath: '/forsaljning/varderingar'
      preLoaderRoute: typeof AuthenticatedForsaljningVarderingarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/konto/': {
      id: '/_authenticated/konto/'
      path: '/konto'
      fullPath: '/konto/'
      preLoaderRoute: typeof AuthenticatedKontoIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/overenskommelse/': {
      id: '/_authenticated/overenskommelse/'
      path: '/overenskommelse'
      fullPath: '/overenskommelse/'
      preLoaderRoute: typeof AuthenticatedOverenskommelseIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/overenskommelse/kostnadsslag': {
      id: '/_authenticated/overenskommelse/kostnadsslag'
      path: '/overenskommelse/kostnadsslag'
      fullPath: '/overenskommelse/kostnadsslag'
      preLoaderRoute: typeof AuthenticatedOverenskommelseKostnadsslagRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/overenskommelse/parter': {
      id: '/_authenticated/overenskommelse/parter'
      path: '/overenskommelse/parter'
      fullPath: '/overenskommelse/parter'
      preLoaderRoute: typeof AuthenticatedOverenskommelseParterRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/overenskommelse/tillagg': {
      id: '/_authenticated/overenskommelse/tillagg'
      path: '/overenskommelse/tillagg'
      fullPath: '/overenskommelse/tillagg'
      preLoaderRoute: typeof AuthenticatedOverenskommelseTillaggRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/overenskommelse/versioner': {
      id: '/_authenticated/overenskommelse/versioner'
      path: '/overenskommelse/versioner'
      fullPath: '/overenskommelse/versioner'
      preLoaderRoute: typeof AuthenticatedOverenskommelseVersionerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/system/anvandare': {
      id: '/_authenticated/system/anvandare'
      path: '/system/anvandare'
      fullPath: '/system/anvandare'
      preLoaderRoute: typeof AuthenticatedSystemAnvandareRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/system/hushall': {
      id: '/_authenticated/system/hushall'
      path: '/system/hushall'
      fullPath: '/system/hushall'
      preLoaderRoute: typeof AuthenticatedSystemHushallRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/system/inbjudningar': {
      id: '/_authenticated/system/inbjudningar'
      path: '/system/inbjudningar'
      fullPath: '/system/inbjudningar'
      preLoaderRoute: typeof AuthenticatedSystemInbjudningarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/system/revision': {
      id: '/_authenticated/system/revision'
      path: '/system/revision'
      fullPath: '/system/revision'
      preLoaderRoute: typeof AuthenticatedSystemRevisionRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/transaktioner/': {
      id: '/_authenticated/transaktioner/'
      path: '/transaktioner'
      fullPath: '/transaktioner/'
      preLoaderRoute: typeof AuthenticatedTransaktionerIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/transaktioner/historik': {
      id: '/_authenticated/transaktioner/historik'
      path: '/transaktioner/historik'
      fullPath: '/transaktioner/historik'
      preLoaderRoute: typeof AuthenticatedTransaktionerHistorikRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/transaktioner/vantar': {
      id: '/_authenticated/transaktioner/vantar'
      path: '/transaktioner/vantar'
      fullPath: '/transaktioner/vantar'
      preLoaderRoute: typeof AuthenticatedTransaktionerVantarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/bilaga/': {
      id: '/api/bilaga/'
      path: '/api/bilaga'
      fullPath: '/api/bilaga/'
      preLoaderRoute: typeof ApiBilagaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/bilaga/$id': {
      id: '/api/bilaga/$id'
      path: '/api/bilaga/$id'
      fullPath: '/api/bilaga/$id'
      preLoaderRoute: typeof ApiBilagaIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedSimulatorRoute: typeof AuthenticatedSimulatorRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedForsaljningSlutavrakningRoute: typeof AuthenticatedForsaljningSlutavrakningRoute
  AuthenticatedForsaljningVarderingarRoute: typeof AuthenticatedForsaljningVarderingarRoute
  AuthenticatedOverenskommelseKostnadsslagRoute: typeof AuthenticatedOverenskommelseKostnadsslagRoute
  AuthenticatedOverenskommelseParterRoute: typeof AuthenticatedOverenskommelseParterRoute
  AuthenticatedOverenskommelseTillaggRoute: typeof AuthenticatedOverenskommelseTillaggRoute
  AuthenticatedOverenskommelseVersionerRoute: typeof AuthenticatedOverenskommelseVersionerRoute
  AuthenticatedSystemAnvandareRoute: typeof AuthenticatedSystemAnvandareRoute
  AuthenticatedSystemHushallRoute: typeof AuthenticatedSystemHushallRoute
  AuthenticatedSystemInbjudningarRoute: typeof AuthenticatedSystemInbjudningarRoute
  AuthenticatedSystemRevisionRoute: typeof AuthenticatedSystemRevisionRoute
  AuthenticatedTransaktionerHistorikRoute: typeof AuthenticatedTransaktionerHistorikRoute
  AuthenticatedTransaktionerVantarRoute: typeof AuthenticatedTransaktionerVantarRoute
  AuthenticatedForsaljningIndexRoute: typeof AuthenticatedForsaljningIndexRoute
  AuthenticatedKontoIndexRoute: typeof AuthenticatedKontoIndexRoute
  AuthenticatedOverenskommelseIndexRoute: typeof AuthenticatedOverenskommelseIndexRoute
  AuthenticatedTransaktionerIndexRoute: typeof AuthenticatedTransaktionerIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedSimulatorRoute: AuthenticatedSimulatorRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedForsaljningSlutavrakningRoute:
    AuthenticatedForsaljningSlutavrakningRoute,
  AuthenticatedForsaljningVarderingarRoute:
    AuthenticatedForsaljningVarderingarRoute,
  AuthenticatedOverenskommelseKostnadsslagRoute:
    AuthenticatedOverenskommelseKostnadsslagRoute,
  AuthenticatedOverenskommelseParterRoute:
    AuthenticatedOverenskommelseParterRoute,
  AuthenticatedOverenskommelseTillaggRoute:
    AuthenticatedOverenskommelseTillaggRoute,
  AuthenticatedOverenskommelseVersionerRoute:
    AuthenticatedOverenskommelseVersionerRoute,
  AuthenticatedSystemAnvandareRoute: AuthenticatedSystemAnvandareRoute,
  AuthenticatedSystemHushallRoute: AuthenticatedSystemHushallRoute,
  AuthenticatedSystemInbjudningarRoute: AuthenticatedSystemInbjudningarRoute,
  AuthenticatedSystemRevisionRoute: AuthenticatedSystemRevisionRoute,
  AuthenticatedTransaktionerHistorikRoute:
    AuthenticatedTransaktionerHistorikRoute,
  AuthenticatedTransaktionerVantarRoute: AuthenticatedTransaktionerVantarRoute,
  AuthenticatedForsaljningIndexRoute: AuthenticatedForsaljningIndexRoute,
  AuthenticatedKontoIndexRoute: AuthenticatedKontoIndexRoute,
  AuthenticatedOverenskommelseIndexRoute:
    AuthenticatedOverenskommelseIndexRoute,
  AuthenticatedTransaktionerIndexRoute: AuthenticatedTransaktionerIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  InbjudanTokenRoute: InbjudanTokenRoute,
  ApiBilagaIdRoute: ApiBilagaIdRoute,
  ApiBilagaIndexRoute: ApiBilagaIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
